---
title: "Arbutus Cloud Computing Guide"
author: Sky (Kehan) Sheng
---

## Welcome

This guide provides comprehensive instructions for working with Arbutus, Compute Canada's OpenStack cloud platform, and managing object storage with S3.

## Author

**Sky (Kehan) Sheng** 

* University of British Columbia Animal Welfare Program
* [skysheng.io](https://www.skysheng.io)

## Quick Cheatsheet (For Returning Users)

If you've already completed the tutorials and just need to get back up and running quickly, here are the essential commands:

```bash
# Move to the local directory where you cloned https://github.com/skysheng7/awp-arbutus-login.git
cd awp-arbutus-login

# Build and start the Docker container with OpenStack tools 
# (make sure you have Docker Desktop running)
make docker

# Load your OpenStack credentials into the environment
source def-ubcawp-dev-openrc.sh

# Test S3 connection (if already configured)
s3cmd ls
```

---

## Full Tutorials

1. **[Getting Started](tutorial/getting-started.html)** - Prerequisites and installation
2. **[Arbutus Authentication](tutorial/arbutus-auth.html)** - Setting up OpenStack authentication
3. **[S3 Storage Setup](tutorial/s3-setup.html)** - Configuring s3cmd for object storage
4. **[S3 Operations](tutorial/s3-operations.html)** - Working with buckets and files
5. **[Command Cheatsheet](tutorial/cheatsheet.html)** - Quick reference for common commands

## What is Arbutus?

Arbutus is Compute Canada's OpenStack cloud platform that provides:

- Virtual machines and compute resources
- Object storage (S3-compatible)
- Networking and security groups
- Image management

## Additional Resources

- [OpenStack CLI Guide](https://docs.alliancecan.ca/wiki/OpenStack_command_line_clients)
- [Digital Research Alliance of Canada Documentation](https://docs.computecanada.ca/)
- [OpenStack Client Documentation](https://docs.openstack.org/python-openstackclient/latest/)
- [s3cmd setup](https://docs.alliancecan.ca/wiki/Accessing_object_storage_with_s3cmd)


